name: Checks

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run unit tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "^3.12"

      - name: Install PortAudio
        run: sudo apt install -y portaudio19-dev

      - name: Install Poetry
        run: pip install poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Test and collect
        run: poetry run inv coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
